rocksdb:
 - 6.2
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.10                  # [osx]
macos_min_version:         # [osx]
  - 10.10                  # [osx]
c_compiler_version:
  - 7                      # [linux64]
  - 9                      # [osx]
cxx_compiler_version:
  - 7                      # [linux64]
  - 9                      # [osx]
