{% set name = "cockroach" %}
{% set version = "19.2.8" %}

package:
  name: go-{{ name|lower }}
  version: {{ version }}

source:
  folder: gopath
  url: https://binaries.cockroachdb.com/{{ name }}-v{{ version }}.src.tgz
  sha256: 6079237f9117c48d5eff449a2e3acd56aedb475149735d2689e8b9505a0aa9ee
  patches:
    - 0001-use-conda-forge-dependencies.patch

build:
  number: 1
  #pin_depends: strict
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("go-cgo") }} >=1.12.17,<1.13
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake >=3.8,<4
    - protobuf ==3.6.0
    - yarn
  host:
    - jemalloc
    - libprotobuf
    - libedit
    - rocksdb
  run:
    - {{ pin_compatible('libedit', max_pin="x.x") }}

test:
  commands:
    - cockroach version
    - cockroach start-single-node --insecure --background --host localhost
    - cockroach workload init startrek
    - cockroach sql --insecure -d startrek -e 'select quote from quotes limit 1;'
    - cockroach quit --insecure

about:
  home: http://cockroachlabs.com
  license: LicenseRef-BSL-1.1
  license_file: gopath/src/github.com/cockroachdb/cockroach/licenses/BSL.txt
  summary: A disaster-surviving, cloud-native SQL database for building global, scalable cloud services.
  description: |
    CockroachDB is a distributed SQL database built on a transactional and
    strongly-consistent key-value store. It scales horizontally; survives disk,
    machine, rack, and even datacenter failures with minimal latency disruption and
    no manual intervention; supports strongly-consistent ACID transactions; and
    provides a familiar SQL API for structuring, manipulating, and querying data.
  doc_url: https://www.cockroachlabs.com/docs
  dev_url: https://github.com/cockroachdb/cockroach

extra:
  recipe-maintainers:
    - sodre
